### ISSUE TITLE
`GET /channels` request needs to specify the workspace id. 

### ISSUE THREAD

**Issue by 7adidaz** [Matterwise/docs#5]
maybe update it to `GET /channels/{workplace_id}` or move it to the `workspace` API set.

**Comment by moaazelsayed1** [comment]
Note that the global `servers` array contains `/workspaces`, as the most of endpoints are workspace-related. Of course we can override this at the operation level when needed. 
```
- url: "{protocol}://localhost:{port}/workspaces/{workspace_id}"
    variables:
      protocol:
        default: http
        enum:
          - http
          - https
      port:
        enum:
          - "443"
          - "8443"
        default: "8443"
      workspace_id:
        default: "1"
        description: workspace id
```
