### ISSUE TITLE
Foreign keys must be read-write

### ISSUE THREAD

**Issue by moaazelsayed1** [Matterwise/docs#9]
For example in `Message` schema the client should set the `channel_id`, `parent_message_id`, and `workspace_id`.
```
sender_id:
          type: string
          format: uuid
          readOnly: true
channel_id:
          type: string
          format: uuid
          readOnly: true
parent_message_id:
          type: string
          format: uuid
          readOnly: true
workspace_id:
          type: string
          format: uuid
          readOnly: true
```
